### ISSUE TITLE
Only download new chapters with inline

### ISSUE THREAD

**Issue by nickexyz** [metafates/mangal#100]
### Feature Description

Thanks for making a great tool!
When downloading with inline, for example:
`inline --source "Sourcename" --query "Manganame" --manga first --chapters all -d`
It seems like all chapters get downloaded every time, which isn't great if you are using mangal to do batch downloads of multiple series.

### Solution you would like

Would be awesome if there is a --check-local flag or something like that.
All that's really needed is to check if the file exists before downloading.

I guess there could be instances where a chapter is updated, which then would not be downloaded.
That would not an issue for me at least.

### Additional context

From what I can see, this is not a feature yet.
Hopefully I'm wrong, and in that case I apologize for creating this issue.

**Comment by metafates** [comment]
Yo!

You are right, this isn't a thing right now. I can implement it, no problem

**Comment by nickexyz** [comment]
That would be awesome, thanks!

**Comment by metafates** [comment]
No need for any extra flags - by default it will check for existing chapter. Tho, it can be disabled at the config.

Thanks for feature suggestion!

**Comment by nickexyz** [comment]
Wow, that is impressive!
I was hoping for the feature this month, and got it within a hour.

Thanks again, awesome work!
