### ISSUE TITLE
Ability to pass anilist id in inline mode

### ISSUE THREAD

**Issue by oae** [metafates/mangal#106]
### Feature Description

Sometimes there can be more than one anilist match and if we are using the inline mode, it is not possible to select one.

### Solution you would like

Can you add an ability to pass an anilist id in inline mode?

### Additional context

https://github.com/oae/kaizoku/issues/6

**Comment by metafates** [comment]
Hello! 

It's a good idea! I'll try to add it

**Comment by metafates** [comment]
It was easier than I though 😃

The implementation looks like that

```shell
# Get anilist manga by id. Will print manga to stdout in json format
mangal inline anilist search --id 30013

# Search anilist manga by name. Will print manga to stdout in json format
mangal inline anilist search --name "one piece"

# Bind some manga to the specific anilist one. Will return error if id is invalid
# Will bind all mangas that has "One piece" as title to Anilist one with id 30013
mangal inline anilist set --name "One Piece" --id 30013

# Get binding. Will print manga to stdout in json format
mangal inline anilist get --name "One Piece"
```

Will merge into the main branch soon
