### ISSUE TITLE
How do I build the binary?

### ISSUE THREAD

**Issue by schklom** [metafates/mangal#107]
### Feature Description

I'm always frustrated when there are 0 build instructions.

I want to build this app on an ARM device, but can't find any instructions.
I am not a Go developer, but I can use Dockerfiles. Usually, they build the binaries from source. Otherwise, what's the point? I can download the binary myself, no need for a Docker image.

### Solution you would like

Shell instructions that build the binary would be nice. An official Dockerfile that runs these instructions would be even better.
Both would be perfect.

### Alternatives you have considered

I see a Makefile, but don't really know how to use these. Do I build the binary by executing `make`?

### Additional context

Typically, the basics of a Dockerfile are to put shell instructions into lines e.g.
```dockerfile
RUN mkdir /aaa
RUN echo 123
```
and to execute the binary in the end with `CMD` or `ENTRYPOINT` or [both](https://docs.docker.com/engine/reference/builder/#cmd).

**Comment by metafates** [comment]
Hi!

Sure, I can make instruction more clear.

If you run `make` It will show available options.
- To build: `make build`
- To install (build and add to path): `make install`

It will automatically build binary for your arch. You if want cross compilation you'll have to set env variables to specify what os and arch you'd like to build for

```shell
GOOS=darwin GOARCH=386 make build
```

[Available GOOS and GOARCH](https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63)

Hope it helps!

**Comment by schklom** [comment]
@metafates Thanks for making clear instructions!
I am not sure how one would run the binary from a Docker image because it seems to require manual configuration.
Here is a working Dockerfile that builds the binary from source and creates a small image, if it helps :)
```dockerfile
FROM golang:latest AS builder

ENV MANGAL_DOWNLOADER_PATH=/downloads
ENV MANGAL_UID=1000
ENV MANGAL_GID=1000

COPY . /mangal-build
WORKDIR /mangal-build
RUN GOOS=linux GOARCH=arm64 make build

FROM alpine:latest

COPY --from=builder --chown=${MANGAL_UID}:${MANGAL_GID} /mangal-build/mangal /mangal
COPY --from=builder --chown=${MANGAL_UID}:${MANGAL_GID} /mangal-build/config /config
COPY --from=builder --chown=${MANGAL_UID}:${MANGAL_GID} /mangal-build/downloads ${MANGAL_DOWNLOADER_PATH}

USER ${MANGAL_UID}:${MANGAL_GID}

WORKDIR /

ENTRYPOINT ["/mangal"]
```
