### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Sebbito** [metafates/mangal#11]
After a quick apt-get install golang-go i get those errors on installation:
```
go install github.com/metafates/mangal@latest
can't load package: package github.com/metafates/mangal@latest: can only use path@version syntax with 'go get'
go get github.com/metafates/mangal@latest
go get github.com/metafates/mangal@latest: can't request explicit version of path in main module
```

Infos:
Go Version: go1.13.8 linux/amd64
System: Ubuntu 20.04.4 LTS on Windows 10 x86

**Comment by metafates** [comment]
Hello! 

What version of go are you using? (`go version`)

**Comment by metafates** [comment]
Hello!

You're using an old version of go, try to install go from [snap](https://snapcraft.io/go)

`sudo snap install --classic go`

**Comment by Sebbito** [comment]
Snap didn't work since it isn't intended to be used on WSL but you were correct. A newer version of Go fixed it.
I downloaded it from the official [source](https://go.dev/doc/install) and that fixed it.
