### ISSUE TITLE
Wrong ComicInfo.xml generation when date in metadata is incomplete

### ISSUE THREAD

**Issue by oae** [metafates/mangal#114]
### Describe the bug

If the date field is incomplete in anilist (for example year and month exist but the day is null), mangal writes `0` as the value in ComicInfo.xml. This causes komga to fail.

![image](https://user-images.githubusercontent.com/1043714/197777842-5ccacc01-e4c9-450f-8d59-83f6187ffb73.png)

### Reproduction steps

You can see an example manga in this [link](https://anilist.co/graphiql?query=query%20%7B%0A%20%20Page%20(page%3A%201%2C%20perPage%3A%2030)%20%7B%0A%20%09%09media%20(search%3A%22Battle%20through%20the%20heavens%22%2C%20type%3A%20MANGA)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20title%20%7B%0A%20%20%20%20%20%20%20%20romaji%0A%20%20%20%20%20%20%20%20english%0A%20%20%20%20%20%20%20%20native%0A%20%20%20%20%20%20%20%20userPreferred%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20startDate%20%7B%0A%20%20%20%20%20%20%20%20year%0A%20%20%20%20%20%20%20%20month%0A%20%20%20%20%20%20%20%20day%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20endDate%20%7B%0A%20%20%20%20%20%20%20%20year%0A%20%20%20%20%20%20%20%20month%0A%20%20%20%20%20%20%20%20day%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)

![image](https://user-images.githubusercontent.com/1043714/197777000-aa6bee8c-413b-4971-a96d-7dc3e7aea437.png)

### Expected behavior

It should not put an invalid value for dates.

### Operating System

Linux

**Comment by metafates** [comment]
Hi! Thanks for noticing! Will fix
