### ISSUE TITLE
Disable date generation for each chapter in ComicInfo.xml

### ISSUE THREAD

**Issue by metafates** [metafates/mangal#117]
### Feature Description

https://github.com/oae/kaizoku/issues/11#issuecomment-1291918898

>It's kinda annoying that the comicinfo.xml contains the publish date of the series and not the chapter, which makes the date of every chapter in tachiyomi (via komga) show up as released on the publish date for the series.
>
>So a chapter released last week might be marked as released in 2014 if that is when the manga first started.

### Solution you would like

Something like

```shell
mangal config set --key "metadata.comic_info_xml_add_date" --value false
```

### Alternatives you have considered

Disable ComicInfo generation at all or manually remove `Year`, `Month` and `Day` tags from it

**Comment by vodkapmp** [comment]
Would it be possible to have a scraper grab the date for when the chapter was posted on the source you're using, and using that date for the ComicInfo.xml?

**Comment by metafates** [comment]
> Would it be possible to have a scraper grab the date for when the chapter was posted on the source you're using, and using that date for the ComicInfo.xml?

Unfortunately, it's not possible for 9/10 cases. Manga sites rarely (≈never) provide such data and neither does Anilist

**Comment by vodkapmp** [comment]
> > Would it be possible to have a scraper grab the date for when the chapter was posted on the source you're using, and using that date for the ComicInfo.xml?
> 
> Unfortunately, it's not possible for 9/10 cases. Manga sites rarely (≈never) provide such data and neither does Anilist

Probably not worth the hassle if it's not going to be used much anyway, though the sites I mostly use (Mangasee, manganelo, and mangadex) all do provide that info.
I know if there is no comicinfo.xml then apps like Tachiyomi will display what I assume is the edit date of the file. Which should be the date when the chapter was downloaded, which to be fair is a good enough date to have on it.

**Comment by metafates** [comment]
It's a good idea actually (download date). 
I would not recommend disabling ComicInfo.xml since it provides some useful data such as genres and tags so I think I can just make an option to enable such dates instead of a series release ones.
