### ISSUE TITLE
Inclusion of Writers / Pencillers etc. in the comicinfo

### ISSUE THREAD

**Issue by Vodes** [metafates/mangal#119]
### Feature Description

It would be nice to have more of the possible metadata filled out. It also adds additional grouping/sorting on stuff like Komga/Kavita if you have them.

### Solution you would like

It should be possible to get these with the anilist api. 
I'd say mapping it like 

Story / Original Story -> Writer
Art -> Penciller

should be fitting.

**Comment by metafates** [comment]
Sure! Should not be difficult
