### ISSUE TITLE
Add setting for ignoring Anilist tags under certain percentage

### ISSUE THREAD

**Issue by vodkapmp** [metafates/mangal#121]
### Feature Description

Anilist often has tags that have a very low percentage, meaning they aren't actually that relevant to the series, or straight up incorrect.
Like for example a single page with slightly suggested nudity in a 1000+ page manga might get it tagged with the nudity tag, but the tag will have sub 10% votes on Anilist, and still be included in the tags.
These tags are usually just incorrect and you'd not want them in your comicinfo.xml

### Solution you would like

An added setting ala this, with the value corresponding with the percentage.
`mangal config set --key "metadata.comic_info_xml_tag_ignore_percentage" --value 50`
I don't know if the tags are used elsewhere, if so maybe it should be a global ignore for pulling the info from Anilist.

### Additional context

There is just a lot of terrible tagging on anilist.

**Comment by metafates** [comment]
Sure! I've been thinking the same lately, some tags are just irrelevant. Will do!
