### ISSUE TITLE
Allow updating metadata of already downloaded files

### ISSUE THREAD

**Issue by oae** [metafates/mangal#124]
### Feature Description

Is it possible to add a command to update ComicInfo.xml, series.json, and cover.jpg of already downloaded files?

### Additional context

We can already update metadata for future chapters with the new anilist command but it doesn't update already downloaded files

**Comment by metafates** [comment]
Hello! In theory - yes, it's possible. But updating ComicInfo.xml requires much more work than cover or series.json. I'll try to do my best

**Comment by metafates** [comment]
Okaay, it was was not easy indeed, but in the end looks like everything works smoothly.

The command will be 

```shell
mangal inline anilist update --path <manga directory>
```

It will update ComicInfo.xml of each CBZ file, download new cover and update series.json 🥳
