### ISSUE TITLE
Empty files when downloading from windows

### ISSUE THREAD

**Issue by Sebbito** [metafates/mangal#13]
**Description**
When downloading any manga via Powershell or Command Line, only blank files with 0B get downloaded, yet it states that the download was successfull. Also if you download via powershell you can't remove them via explorer.

**To Reproduce**
1. Open mangal normally
2. Download any manga (i tested with Jujutsu Kaisen, Naruto, One Piece, The Promised Neverland)
3. Open folder and see the blank files

**Expected behavior**
Standard file type gets downloaded to default location (PDF file to home folder).

**Screenshots**
[Image](https://imgur.com/a/3VtWl8n)

**Desktop:**
 - Browser: Firefox 101.0.1 (64-Bit)
 - OS: Windows 10
 - Version 10.0.19044 Build 19044

**Comment by metafates** [comment]
Hello!

I actually had the same issue today when I was testing with windows. I'll try to fix it ASAP

**Comment by metafates** [comment]
That was a very frustrating bug xd
