### ISSUE TITLE
Exact match manga selector

### ISSUE THREAD

**Issue by oae** [metafates/mangal#131]
### Feature Description

Is it possible to add an exact selector to the manga parameter to match the name from the result list? Something like below;

### Solution you would like

A new selector like below that matches the name;

```bash
mangal inline --source Mangasee --query "Naruto" --manga exact -j
```

### Alternatives you have considered

I tried the following items in order to get the same result;
1. Execute `mangal inline --source Mangasee --query "Naruto" -j`
2. Read the result array and filter the exact matching item
3. And then execute with the index from the result `mangal inline --source Mangasee --query "Naruto" --manga <index> --chapters all -j`

### Additional context

See https://github.com/oae/kaizoku/issues/33

**Comment by metafates** [comment]
Hi, sure! Will do
