### ISSUE TITLE
Tags and Genre are the same

### ISSUE THREAD

**Issue by Vodes** [metafates/mangal#133]
### Describe the bug

Just noticed this on a freshly downloaded manga, 
![image](https://user-images.githubusercontent.com/48185123/201331910-9c8ef1bf-6fab-4f90-a088-ed8f299fc654.png)
and checked the comicinfo to see this

```xml
  <Genre>Martial Arts,Revenge,Male Protagonist,Swordplay,Tragedy,Full Color,Time Skip,Anti-Hero,Shounen,Wuxia</Genre>
  <Tags>Martial Arts,Revenge,Male Protagonist,Swordplay,Tragedy,Full Color,Time Skip,Anti-Hero,Shounen,Wuxia</Tags>
  <Notes>Downloaded with Mangal. https://github.com/metafates/mangal</Notes>
  ```

I did download it through Kaizoku but I don't think Kaizoku interferes with that 

### Operating System

Linux

**Comment by metafates** [comment]
Hey, 

You're right, yes, it's a bug. Thank you!
