### ISSUE TITLE
Documentation for the usage of env variables in the mangal.toml config file

### ISSUE THREAD

**Issue by mephisto3478** [metafates/mangal#136]
### Feature Description

Hey!
I'd like to customize things like the chapter name template, but can't really tell what the possible variables for the name are or what other env variables even do in general.
Have I overseen a documentation for the usage of these?

**Comment by metafates** [comment]
Hello!

You can use this command to see all configuration fields with description for each

```shell
mangal config info
```

For example, if you want to work with chapter name template:

1. Check the description and available variables by running `mangal config info -k downloader.chapter_name_template`
2. Change the value to, say, `{source} {manga} {index}`. To do that either set an env variable `MANGAL_DOWNLOADER_CHAPTER_NAME_TEMPLATE` or use `mangal config set -k downloader.chapter_name_template -v "{source} {manga} {index}"` command


Hope that helps!

P.S. I agree - mangal really lacks proper documentation

**Comment by mephisto3478** [comment]
Thank you very much, that helps indeed!
I've totally overseen the `mangal config info` command in the Configuration section of the README and only used `mangal env`
