### ISSUE TITLE
[Packaging] Gentoo Linux package now exists

### ISSUE THREAD

**Issue by leycec** [metafates/mangal#139]
### Feature Description

`mangal` stuns me with its succinct beauty, Vi-like key bindings, and outrageous support for every manga site I care about. Because of these good things, I now personally maintain a `mangal` package for Gentoo Linux at [`raiagent`](https://github.com/leycec/raiagent) – my third-party Gentoo overlay. Installation is trivial, for which we all give thanks:

```bash
eselect repository enable raiagent
emerge --sync raiagent
emerge mangal
```

Praise be to @metafates!

### Solution you would like

I know you're *crazy* busy, @metafates. But when you get a spare moment this Christmas, would you mind adding the above 3-line installation instructions to a new **"Gentoo Linux"** section of your `README.md`? I'd be happy to submit a PR for this, if you like.

Bros gotta help bros. :smile:

### Alternatives you have considered

Doing nothing but reading manga instead. This is *always* a valid alternative.

### Additional context

Oh – and thanks so much for tracking the `vendor/` directory in both this repository and your release tarballs! Your hard work made a *huge* difference there, @metafates. Without that, I (probably) wouldn't have been able to package `mangal` for Gentoo. :sweat:

**Comment by metafates** [comment]
Awesooooome! Thank you for that! I'll add it to the README a bit later today, or you can make a PR, sure, I'd happy to have more contributors showing in the repository page =)

**Comment by metafates** [comment]
Done! Thank you again!

**Comment by leycec** [comment]
**Wowza!** Thanks so much for the rapid turnaround. All in Gentoo Land applaud thunderously.

Unrelatedly: let it be known that Naoki Urasawa's *20th Century Boys* (*20 Seiki Shounen*) is a mild-melting masterpiece. I slept on it much too long. Now I regret everything. Don't be as foolish as me! The mistakes of the past must be laid to rest. :sleepy:
