### ISSUE TITLE
Windows download/config issue

### ISSUE THREAD

**Issue by jwestern1337** [metafates/mangal#14]
When downloading files on windows it nevers creates the file with a file extension (e.g. .pdf)
Even when specify file type via config or CLI it just saves them as a file (no extension)

**Comment by metafates** [comment]
Hello!

Could you please provide a screenshot? Or maybe you're talking about #13 ?

**Comment by metafates** [comment]
It came to be that windows is really bad at handling paths with whitespaces 😞
