### ISSUE TITLE
How to select download lang on mangadex

### ISSUE THREAD

**Issue by delta-whiplash** [metafates/mangal#157]
Hello I am new on this sofwtare and I want to downloads french release of https://mangadex.org/title/4e7a4a0f-8391-4069-839b-de2352297dab/kakkou-no-iinazuke How can I setup mangal to do this
in CBZ or CBR if possible

**Comment by metafates** [comment]
Hi! 

Mangadex language can be configured via `mangadex.language` key

E.g. 

```bash
# French
mangal config set -k mangadex.language -v fr # it's en by default
```

You can also use `all` value to include all languages

**Comment by delta-whiplash** [comment]
That's nice thank you
Do you support the download in CBR or cbz format ?

**Comment by metafates** [comment]
Yeah, CBZ is supported.

You can use it like this

```bash
# Use CBZ format only for this session
mangal --format cbz

# Use CBZ by default permanently
mangal config set -k formats.use -v cbz # pdf is the default
```

**Comment by delta-whiplash** [comment]
Nice thank you where can I found all documentation about this command to learn alone

**Comment by metafates** [comment]
You can use

```bash
mangal config -k formats.use
```

You'll see the output

<img width="444" alt="Screenshot 2023-02-15 at 00 24 06" src="https://user-images.githubusercontent.com/62389790/218866328-04f986aa-25d1-4c4e-8503-dcf55b57e1c9.png">

**Comment by delta-whiplash** [comment]
Thank you I will check that
