### ISSUE TITLE
Anilist integration for syncing progress

### ISSUE THREAD

**Issue by justchokingaround** [metafates/mangal#16]
**Is your feature request related to a problem? Please describe.**

when I finish my reading session using the read option, I need to either manually go to anilist's website and update my reading progress there or use an external custom script which makes a post request to anilist's api with my tokens

**Describe the solution you'd like**

if possible, i would like a solution integrated withing this project itself

**Describe alternatives you've considered**

Anilist's website manually or external custom script

**Comment by metafates** [comment]
That's a cool idea! I think I'll be able to make it. But I'm not sure how to handle situations where manga found on Anilist does not match the one selected in Mangal

Example
<img width="827" alt="Screenshot 2022-06-18 at 12 23 40" src="https://user-images.githubusercontent.com/62389790/174431461-01f9190b-0ca6-47ad-9607-9c6ff0deffa1.png">
 

I think I could check if two titles are "similar" by using something like Levenshtein distance 🤔 but still this is kinda unreliable.

Or there could some sort of prompt before reading like "Mark %manga_found_on_anilist% %chapter% as read?"

**Comment by justchokingaround** [comment]
so i've looked further into it, and tried to see if it could be done through matching the author's name, but neither anilist nor kitsu's api have that info, so this is all i was able to do, if that helps:

```py
import requests

query = '''
query ($id: Int, $search: String) {
  Page(page: 1, perPage: 10) {
      pageInfo {
        total
        perPage
        }
    media(id: $id, search: $search, format: MANGA) {
        id
        idMal
        format
        title {
            romaji
            english
            native
            userPreferred
        }
    }
  }
}
'''

variables = {
    'search': 'Death Note',
}

url = 'https://graphql.anilist.co'

response = requests.post(url, json={'query': query, 'variables': variables})

print(response.json())
```

but then again, it'll come down to Levenshtein distance

**Comment by EKYS12** [comment]
The android application Tachiyomi, which can be found [here](https://github.com/tachiyomiorg/tachiyomi), solves this issue by adding a sync setting per series in the saved library of a user. After connecting your anilist to tachiyomi, when you open a series page in the app there is a tracker that you can set for anilist (or which ever tracking catalogue service you use, like MAL), and then it will do a query in Anilist with the title of series. You can even edit the query as well. This query will show all the results that anilist pulls up, and you the user can manually set which series it should link to. 
![Screenshot_20220619-233754](https://user-images.githubusercontent.com/101851062/174521002-88be4783-db99-408a-a2a6-06380150e845.jpeg)
![Screenshot_20220619-233803](https://user-images.githubusercontent.com/101851062/174521015-508d0ce8-1df5-4fd4-8303-c1a1a4f2a97e.jpeg)

**Comment by metafates** [comment]
Thanks for sharing, that's a nice solution! I'll think about it
