### ISSUE TITLE
Sometimes not finding last chapter

### ISSUE THREAD

**Issue by aenon83** [metafates/mangal#161]
### Describe the bug

Sometines the app doesn't show the last chapter. I don't know if it's a bug or the api from the site doesn't show recent chapters.

For example, always using Mangapill as source:

- If I search for **Komi-san wa, Comyushou desu.**, from the following [url](https://mangapill.com/manga/2431/komi-san-wa-comyushou-desu)
   - The app shows as last chapter the chapter 391
   - The last chapter in the web is chapter 392

- If I search for **Ijiranaide, Nagatoro-san**, from the following [url](https://mangapill.com/manga/1892/ijiranaide-nagatoro-san)
   - The app shows as last chapter the chapter 121
   - The last chapter in the web is chapter 122

### Reproduction steps

1. Search for Ijiranaide, Nagatoro-san
2. Select the one with the following url: https://mangapill.com/manga/1892/ijiranaide-nagatoro-san
3. Search the last chapter and it is 121
4. The last chapter in the web is 122

### Expected behavior

The last chapter in the app should be 122

### Operating System

Linux

**Comment by metafates** [comment]
Hi!

I can't reproduce this 

<img width="587" alt="Screenshot 2023-02-21 at 12 28 26" src="https://user-images.githubusercontent.com/62389790/220304892-398bdae0-3e76-43a7-a4ea-e97110c8928b.png">

**Comment by aenon83** [comment]
For me it shows only 130 chapters.

Do I need to refresh some cache or something like that?

I don't know if it matters, but I'm using Ubuntu and I just tried to reinstall it with:
`curl -sSL mangal.metafates.one/install | sh`

![Screenshot_20230221_103243](https://user-images.githubusercontent.com/13394437/220305856-074613d4-1982-447a-9c37-89b35ce3e889.png)

**Comment by aenon83** [comment]
I deleted the folder **~/.cache/mangal**, and now I can see all the chapters.

**Comment by metafates** [comment]
Oh, right... You can also use `mangal clear --cache`

**Comment by aenon83** [comment]
Thanks!
