### ISSUE TITLE
EPUB Format

### ISSUE THREAD

**Issue by Ambushfall** [metafates/mangal#166]
### Feature Description

Plain and simple, I've noted this was mentioned in #17 

Afterwards there were no mentions of it being removed, or dropping support.
 

### Solution you would like

Formats.use to have support for epub

### Alternatives you have considered

Download as pdf or plain images and then use an external script or online converter.

**Comment by metafates** [comment]
Hi,

The problem is that ePub isn't suitable for image-only content. Mangal used to support ePub, but I removed this feature soon after.

**Comment by Ambushfall** [comment]
> Hi,
> 
> The problem is that ePub isn't suitable for image-only content. Mangal used to support ePub, but I removed this feature soon after.

Understandable, I was simply confused by no mention of this.

Thank you for taking the time to answer to this! ^^

Mangal is amazing as is 💯
