### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by federicotorrielli** [metafates/mangal#174]
### Describe the bug

When installing on Nobara (Fedora spin):

![image](https://github.com/metafates/mangal/assets/31370059/5e612816-3383-4d49-9925-80b97b9cd551)

### Operating System

Linux

**Comment by raj23689** [comment]
Did you updated your system? Cause I am not facing any issue like that?

**Comment by federicotorrielli** [comment]
Now it's working, closing the issue
