### ISSUE TITLE
mangadex's default content rating filters

### ISSUE THREAD

**Issue by nepxxx** [metafates/mangal#200]
is there any way for me to search for manga that are rated as _erotica_
one example is this manga [https://mangadex.org/title/f4247b21-e8ff-46ae-9f92-fc04f6641188/aitsu-no-kanojo](url)
when i tried to look it up on mangal, it only shows the pre-serialization version of it, which is tagged as _suggestive_
![417 - 2024-January-19 (14 44 34)  1056x536   WindowsTerminal](https://github.com/metafates/mangal/assets/63631875/466da1f6-a094-44ca-ac3c-5566f006b0f3)
thanks, and sorry if i did something wrong, I'm not familiar with how github works.

**Comment by JorgeLNJunior** [comment]
@nepxxx try `mangal config set -k mangadex.nsfw -v true`
