### ISSUE TITLE
Not getting updated chapters from Mangapill

### ISSUE THREAD

**Issue by sinicide** [metafates/mangal#203]
### Describe the bug

Using Mangal 4.0.6 from AUR
When searching for title `Kargurabachi` I only see up to 16 chapters, however on site it's currently up to 24 as of March 10, 2024.

### Reproduction steps

Select Mangapill as Source
Search for Kagurabachi
See that total chapter count is only 16.

### Expected behavior

Expected to see up to 24 as of March 10th, 2024.

### Operating System

Linux

**Comment by sinicide** [comment]
It took me a while, but I realized that I needed to clear cache with `mangal clear -c`

I'm not sure why the cache doesn't get invalidated.
Does anyone know where this cache file is? It's not in my `/.config/mangal/` user home directory.

**Comment by raj23689** [comment]
If i am not wrong they are either on `~/local/.cache` or `~/.local/share/.cache` or on `~/.cache`
 No caches are stored under `~/.config` dir.
 
 If your issue is resolved please close this issue.

**Comment by sinicide** [comment]
Thanks, that's what I needed to know, `~/.cache/mangal` is where my mangal cache is located. Closing this out.
