### ISSUE TITLE
Crashes when pressing space or enter on empty list

### ISSUE THREAD

**Issue by metafates** [metafates/mangal#21]
**Describe the bug**
When pressing select button (space or enter) on empty list (e.g. when nothing was found) mangal crashes

**To Reproduce**
1. Search for manga that does not exist (e.g. type something like 'faofigagjiaogj')
2. Press space or enter
3. See error

**Expected behavior**
It is expected that nothing happens

**System**
 - OS: MacOS Ventura
 - Go Version 1.18.3
 - Mangal 1.5

**Comment by raj23689** [comment]
This behaviour happens in Arch-Linux too. I just checked it.
