### ISSUE TITLE
Invalid character names in downloaded chapters

### ISSUE THREAD

**Issue by arabcoders** [metafates/mangal#33]
### Describe the bug

Right now it seems the tool uses whatever the chapter name is as filename, which is good idea, however some manga and or chapters uses characters which are illegals in windows. 

For example, Lets take Berserk as example the first 3 chapters are named:

```
'[1] Vol.1 Chapter 0.01: The Black Swordsman.pdf'
'[2] Vol.1 Chapter 0.02: The Brand.pdf'
'[3] Vol.1 Chapter 0.03: The Guardians Of Desire (1).pdf'
```

they works correctly in Linux host, however viewing them via windows produce file names like

![xx](https://user-images.githubusercontent.com/1621552/175827824-4948c66f-24f6-413e-b23b-0c42071032a3.png)

you could see list of those characters here for example  

https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names

### Operating System

Windows

### Checks

- [X] I'm using the latest version of Mangal

**Comment by metafates** [comment]
You mean it happens when you download chapters from linux and then open the folder via remote access on Windows? That's actually something I didn't think of😳

Will fix it!

**Comment by arabcoders** [comment]
> You mean it happens when you download chapters from linux and then open the folder via remote access on Windows? That's actually something I didn't think of😳
> 
> Will fix it!

Indeed, people usually use NAS or media server and then consume that data on other devices.

**Comment by arabcoders** [comment]
If i may also bother you if you can add padding setting to have files e.g. [001-0001] right now files are not sorted naturally starting with 

```
'[1] Chapter 1 : Romance Dawn.cbz'
'[20] Chapter 14 : Reckless.cbz'
'[21] Chapter 15 : Gong.cbz'
'[2] Chapter 1.1 : Romance Dawn [Version 1].cbz'
```

this is how the files are named, they are not sequential

**Comment by metafates** [comment]
Sure!
