### ISSUE TITLE
Unable to change download path in config.toml

### ISSUE THREAD

**Issue by lo-maxwell** [metafates/mangal#49]
### Describe the bug

I'm trying to download manga to a specific folder, but mangal keeps downloading to some temporary folder instead regardless of what I put in the download path. I am using the default config file (from config init) with only the download path changed to 
`download_path = '/mangal/someFolder'`

### Reproduction steps

1. Change download_path in config.toml
2. Download manga chapter (currently using chapter 1 of one piece on manganelo)
3. Chapter is downloaded to a folder called 'private/var/folders/0m/zj0991.../T'

### Expected behavior

Chapter should be downloaded to the specified filepath.

### Operating System

macOS

### Checks

- [X] I've used `mangal doctor` and it didn't help

**Comment by metafates** [comment]
Hello! Try this `download_path = '$HOME/mangal/someFolder'`

And you said that it downloads chapter to the `private/var/folders/0m/zj0991.../T` so looks like you are not downloading but trying to read instead by pressing <kbd>r</kbd>. Try pressing space to select a chapter(s) and then press <kbd>enter</kbd> to download it

**Comment by lo-maxwell** [comment]
Yeah that was the issue, was pressing r. Thank you!
