### ISSUE TITLE
better debug info

### ISSUE THREAD

**Issue by tulx17** [metafates/mangal#50]
### Feature Description

I added custom scrapper for my source but nothing got scrapped, or yes. I really don't know what is happening or any information to fix that problem. All I got was

```
Checking if latest version is used... OK
Checking config... OK
Please, enter a manga title to test customsource: isekai
Checking source customsource... Fail
Source customsource is not available
Try to reinitialize your config with mangal config init --force
Note, that this will overwrite your current config
```

Why did the source not available? How can the default source solve my problem?

### Solution you would like

Add a debug flag or atleast write the log somewhere

**Comment by metafates** [comment]
Agree, it's not clear what is happening. I'll add more information, sure! What it tries to do is to search for manga with the title you entered and download the first chapter of the first found manga

**Comment by metafates** [comment]
You could say that now it is not a doctor but just a nurse 😛

**Comment by tulx17** [comment]
Nice. Now I can see a 403 status code. I haven't work with Go before, but I'll try to inspect the http client or somethings like that here
