### ISSUE TITLE
Updated Docker container build

### ISSUE THREAD

**Issue by arabcoders** [metafates/mangal#52]
Hi, I've made an updated docker container build to take advantage of the new ENV variables.

```Dockerfile
FROM alpine:latest

ENV MANGAL_VERSION=v2.1.1
ENV MANGAL_CONFIG_PATH=/config/mangal.toml
ENV MANGAL_DOWNLOAD_PATH=/downloads
ENV MANGAL_USER=abc
ENV MANGAL_UID=1000
ENV MANGAL_GID=1000

WORKDIR "/config"

RUN mkdir -p "${MANGAL_DOWNLOAD_PATH}" && addgroup -g "${MANGAL_GID}" "${MANGAL_USER}" && adduser \
    --disabled-password \
    --gecos "" \
    --home "$(pwd)" \
    --ingroup "${MANGAL_USER}" \
    --no-create-home \
    --uid "${MANGAL_UID}" \
    "${MANGAL_USER}" && \
    chown abc:abc /config "${MANGAL_DOWNLOAD_PATH}"

ADD https://github.com/metafates/mangal/releases/download/${MANGAL_VERSION}/mangal-linux-amd64 /usr/local/bin/mangal

RUN chmod +x /usr/local/bin/mangal

USER "${MANGAL_USER}"

ENTRYPOINT ["/usr/local/bin/mangal"]
```

I think `MANGAL_CONFIG_PATH` is kind of incorrectly named, as of `v2.1.1` it points to a `FILE` directly not a `PATH`, this might cause misinterpretation as i did when i was updating my docker container. I think it should take `PATH` which gives you the possibility in the future to migrate config files when breaking changes happens.

For example, right now config is at `mangal_v1.toml`, in the future you make breaking change, you can create `mangal_v2.toml` and migrate settings from `mangal_v1.toml`.

Also, making more config options configurable via ENV variables is really helpful. prime example at least in my case is `formats.default` i always set it to `cbz`

**Comment by metafates** [comment]
Hi! You mean making `MANGAL_CONFIG_PATH` point to the config directory and then mangal will choose which config file to use?

**Comment by arabcoders** [comment]
> Hi! You mean making `MANGAL_CONFIG_PATH` point to the config directory and then mangal will choose which config file to use?

In essence yes, it should point to directory instead of a file.

**Comment by metafates** [comment]
Okay, that makes more sense, agree. Will do!
