### ISSUE TITLE
[source request] mangadex/comick(.)fun

### ISSUE THREAD

**Issue by edgehub-cloud** [metafates/mangal#54]
### Feature Description

Uncompressed sources along with fast cache

### Solution you would like

Can you please add the usage of their api
Since both of these sources have the most chapters

**Comment by metafates** [comment]
That's something I want too! Right now it's not possible without changing internal structure, because the way scrapers work. But I can make mangadex a special case and add support for it. Not sure when I will do it tho, but I hope in a range of a month 🧑‍🔧

**Comment by edgehub-cloud** [comment]
ALRIGHT
