### ISSUE TITLE
Termux support

### ISSUE THREAD

**Issue by rihaq** [metafates/mangal#80]
### Feature Description

https://stackoverflow.com/q/38959067/7361270

### Solution you would like

https://stackoverflow.com/q/38959067/7361270

### Alternatives you have considered

NA

### Additional context

NA

**Comment by metafates** [comment]
Hi! 

Thank you for the solution. There was the exact same problem with termux #57

Unfortunately, I don’t have an android nor vm for it, so I can’t test it. If someone wish to do it, I would appreciate that

**Comment by rihaq** [comment]
@metafates you can use Android IDE

**Comment by rihaq** [comment]
https://developer.android.com/studio/run/managing-avds

**Comment by rihaq** [comment]
https://github.com/termux/termux-packages/pull/9721

**Comment by metafates** [comment]
OK, I'll try, but not sure when. I'll let you know as soon as there is any progress

**Comment by metafates** [comment]
Update: I was able to get mangal working under Termux! + I've adapted install script to automatically setup everything to get it working. Expect to see it soon 🐳

**Comment by rihaq** [comment]
Oh yeah

**Comment by rihaq** [comment]
@metafates Please don't use proot see this patch https://github.com/termux/termux-packages/pull/9721

**Comment by metafates** [comment]
> @metafates Please don't use proot see this patch [termux/termux-packages#9721](https://github.com/termux/termux-packages/pull/9721)

I'll look into it, thanks

**Comment by metafates** [comment]
okay, so it appears that it needs a specific variation of GO compiler which is very hard to configure with GitHub actions (mangal uses them for automatic release builds). As a workaround, install script will build mangal from source each time, as there aren't any better way to do it. Will be fixes as soon as mangal will be released as a termux package https://github.com/termux/termux-packages/pull/11935
