### ISSUE TITLE
Search with multiple sources at once

### ISSUE THREAD

**Issue by metafates** [metafates/mangal#86]
### Feature Description

Search among multiple sources at the same time

### Solution you would like

Select what sources to use for search in the TUI by pressing <kbd>select</kbd> key

### Additional context

_Originally posted by @omaru-ok in https://github.com/metafates/mangal/discussions/7#discussioncomment-3526605_

**Comment by OmiChrome** [comment]
omg omg my request is getting doen :O :D

**Comment by metafates** [comment]
Here's how it's gonna look like

https://user-images.githubusercontent.com/62389790/188104896-8fb162c0-4a51-4c12-abc0-f89780329cbc.mov

**Comment by OmiChrome** [comment]
noice 

but why we have to install other scrapers separately
i know its easy to install but , why still  separeted  GO, lua ? 

any special reason

**Comment by OmiChrome** [comment]
now im thinking of ani-cli  
but look's like mangal .   🤩 

would be amazing

**Comment by metafates** [comment]
> but why we have to install other scrapers separately i know its easy to install but , why still separeted GO, lua ?

To make mangal extendable, mainly. For example, [Tachiyomi](https://tachiyomi.org) has a similar behaviour (see https://tachiyomi.org/help/guides/getting-started/#installing-an-extension). And since it's "easy" to install other scrapers I think there's no reason to have them come preinstalled by default

**Comment by metafates** [comment]
> now im thinking of ani-cli but look's like mangal . 🤩

Maybe I'll make it in the future 🥴

**Comment by OmiChrome** [comment]
> > now im thinking of ani-cli but look's like mangal . 🤩
> 
> Maybe I'll make it in the future 🥴

if ur reallly thinkig  then there is my thought's  😉 

1. ani-cli tend to be slow for me 🤷  so  i recommend [animdl](https://github.com/justfoolingaround/animdl) over ani-cli
2. also needed some  nice UI 
3. H**ntai support 🥺 
4. more scrapers
5. cross-platfrom  so no worry of being in window 
6. work near to exactly as mangal does . :) 
:D and that's it
