### ISSUE TITLE
PowerShell script to run mangal

### ISSUE THREAD

**Issue by metafates** [metafates/mangal#89]
### Feature Description

It would be awesome to have a powershell script to run mangal just like [this shell script does](https://github.com/metafates/mangal/blob/main/scripts/run)

Here's my attempt to make it [run.ps1](https://github.com/metafates/mangal/blob/main/scripts/run.ps1) but I was not able to test it (I don't have a windows machine and setting up windows vm on m1 is a pain) and I'm not familiar with PowerShell. 

If someone wishes to test it or point out some issues with it I would be very grateful

**Comment by OmiChrome** [comment]
what this does btw?

**Comment by metafates** [comment]
> what this does btw?

Downloads mangal to a temporary folder and runs it from there. This way you can try it without having to install anything. 

https://user-images.githubusercontent.com/62389790/188268826-6ff5c976-2029-4153-8c64-80a46a69b013.mov

**Comment by OmiChrome** [comment]
noice
