### ISSUE TITLE
Mangadex volume creation

### ISSUE THREAD

**Issue by edgehub-cloud** [metafates/mangal#90]
### Feature Description

Smol chapters without able to add meta data from comictagger, even thou komf exist to add data from other places into komga

### Solution you would like

If possible packing chapters into volumes 

### Alternatives you have considered

Making a custom script to do that, but a built in support for some sources would be nice, can probably be used with managdex api to do the same with other sources to fetch chapters per volume

**Comment by metafates** [comment]
Hi! 

Yes, that's possible, tho may be inaccurate for other sources.

The closest you can do right now is 

```
mangal inline --source Manganelo --query "death note" --manga first --chapters "@Vol.1 @"  -d
```

Notice the `--chapters "@Vol.1 @"` selector. It will match all chapters that contain "Vol.1 " in their names

**Comment by edgehub-cloud** [comment]
Maybe just managdex support for chapters, all thou it should match with comick.fun and others if chapter number  are there, ( probably giv users a option to generate volumes based on managdex chapters), please do look into it, thanks for the mangal

**Comment by metafates** [comment]
It works pretty well for now! Will be available in the next release

**Comment by edgehub-cloud** [comment]
Loved to hear this man, good work

**Comment by edgehub-cloud** [comment]
@metafates possible to add convert to volume option for the whole folder {volume} 
thanks
